### ISSUE TITLE
Request:Support for Multiple VST Plugins.

### ISSUE THREAD

**Issue by nanitaro** [Falcosoft/vstdriver#2]
Hello,
Is it possible to use multiple VST plugins with the vstdriver? 
Alternatively, it would be helpful if I could easily switch between multiple VST plugins.
Thanks.

**Comment by Falcosoft** [comment]
Hi,
No, curently it's not possible. Also implementing real-time switching of plugins would require a substantial rewrite of the code.
The best alternative that is availabe today is offered by Windows itself. That is the list of previously loaded/used plugins is preserved in the openfile dialog:
![vstdriver_selectplugin](https://github.com/Falcosoft/vstdriver/assets/40074203/0c6e2890-4aaf-4c53-a467-24e33113863a)

**Comment by Falcosoft** [comment]
Hi,
Wait for the nex release. You will be able to pre-configure 10 VSTi plugins in the configuration dialog and switch beween the plugins at runtime with the help of the tray menu:

![vstdriver_selectplugin2](https://github.com/Falcosoft/vstdriver/assets/40074203/d100d717-4d15-423a-b8a4-d5d4b98bf5bf)

**Comment by nanitaro** [comment]
Hi,
Thanks all for the lighting fast response!

**Comment by Falcosoft** [comment]
What is possible has been added to v2.2.0. 
https://github.com/Falcosoft/vstdriver/releases
